# Generated by Django 5.0.6 on 2024-07-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_up_app', '0003_remove_users_aboutuser_remove_users_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_up_app.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_up_app.users')),
            ],
        ),
    ]
